# Theme Github link: https://github.com/korilin/hexo-theme-particle
# Developer: korilin

# html lang
language: zh

# avatar image url
head_img: images/avatar.png

# home page head info block
head_block_enable: true

# home page head background style.
# If you use a picture as background, you must use the css background-image attribute instead of the background attribute.
# Use image as background ==> home_background: "background-image:url('../home.jpg')"
# Use a color as background ==> home_background: "background: balck"
home_background: "background-image:url('images/home.jpg')"

# Particle theme icon is adopts the ant design vue icons
# Link：https://www.antdv.com/components/icon-cn/

# main menu navigation
menu:
  主页:
    icon:
      name: home
      theme: filled
    src: /
  关于:
    icon:
      name: idcard
      theme: filled
    src: /about
  分类:
    icon:
      name: book
      theme: filled
    src: /categories
  English Blog:
    icon:
      name: compass
      theme: filled
    src: https://en.korilin.com
  記録ブログ:
    icon:
      name: read
      theme: filled
    src: https://jp.korilin.com
# side info card
card:
  enable: true
  description: ["一个热爱开源的开发者"]
  icon_links:
    github:
      icon:
        type: antd-icon
        name: github
        theme: filled
        src:
      link: https://github.com/korilin
    twitter:
      icon:
        type: antd-icon
        name: twitter
        theme:
        src:
      link: https://twitter.com/korilin_dev
  friend_links:
    计算机旅途: /journey
    英文技术博客: https://en.korilin.com
    日语记录博客: https://en.korilin.com

# footer info
footer:
  since: 2018
  # Customize the server domain name ICP
  ICP:
    enable: true
    code: 粤ICP备19149652号

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
  enable: true
  clientID: 30daf96e536313585e82 
  clientSecret: f381bf32648c3e0efe21d5c459987e86c8191f8e 
  repo: cn.korilin.github.io
  owner: korilin 
  admin: korilin 
  language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.

# theme style: full / night / maiden, defalut: full
style: full

# scripts loaded in the end of the body
scripts:
  - /js/particle.js
